name: 'Apply Migration '
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  DB_Project_Path:
    description: 'Enter The Path For The Data Project'
  Startup_Project_Path:
    description: 'Enter The Path For The Startup Project '
  DB_Context:
    description: 'Enter The Name of the DB Context'
  DB_Connection_String:
    description: 'Enter The Database Connection String'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.DB_Project_Path }}
    - ${{ inputs.Startup_Project_Path }}
    - ${{ inputs.DB_Context }}
    - ${{ inputs.DB_Connection_String }}
 
